version: "3.12"

services:
  web:
    build: .
    container_name: miniblog_app
    command: gunicorn miniblog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
